#!/usr/bin/env python3
"""Every faction's roster on the ladder, after the patch: the page to review the lore judgments on.

    python3 rebalance_ladder_view.py      -> ../reports/ladder.md

For each faction, the units in three groups (infantry; cavalry, beasts and chariots; monsters and machines), sorted
by per-model power after the patch, with the vanilla figure, the tier the number lands in, the size, the price
and the ladder's reason. Reading down a faction's list is the question the ladder answers: does the order look like
the lore? Where it does not, the fix is one line in lore_ladder.py.
"""
import json
import os

import unit_model as UM

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "reports", "ladder.md")
BANDS = [("rabble", 0.30), ("levy", 0.45), ("line", 0.75), ("veteran", 1.40), ("elite", 3.00), ("champion", 99.0)]
GROUPS = [("Infantry", ("melee_infantry", "missile_infantry", "monstrous_infantry")),
          ("Cavalry, beasts and chariots", ("melee_cavalry", "missile_cavalry", "monstrous_cavalry", "war_beast", "chariot")),
          ("Monsters and machines", ("monster", "warmachine"))]


def tier(pm, caste):
    if caste in ("monster", "warmachine", "chariot"):
        return "monster"
    if caste in ("monstrous_infantry", "monstrous_cavalry", "war_beast") and pm >= 3.0:
        return "monstrous"
    for name, hi in BANDS:
        if pm < hi:
            return name
    return "champion"


def main():
    R = json.load(open(os.path.join(HERE, "_rebalance.json")))["units"]
    S = {u["key"]: u for u in json.load(open(os.path.join(HERE, "_survey.json")))["units"]}
    with open(OUT, "w") as out:
        w = out.write
        w("# The ladder, faction by faction, after the patch\n\n")
        w("Generated by `tools/rebalance_ladder_view.py`. **pm** is power per model (regiment / entities × 60; an Empire "
          "Knight is 1.00, an Empire Swordsman about 0.5); for monsters and machines the regiment figure is shown instead. "
          "**vanilla → now**; bold where it moved. The tier is where the number lands (`lore_ladder.py` bands); the reason is "
          "the ladder's, the study's, or the price layer's. Read down a faction and ask whether the order is the lore's.\n\n")
        for fac in sorted(UM.FACTION_NAMES, key=lambda x: UM.FACTION_NAMES[x]):
            os_ = [o for o in R if o["faction"] == fac]
            if not os_:
                continue
            w("## %s\n\n" % UM.FACTION_NAMES[fac])
            for title, castes in GROUPS:
                rows = [o for o in os_ if o["caste"] in castes]
                if not rows:
                    continue
                single = title.startswith("Monsters")

                def pm(o, which):
                    p = o["after"]["power_reg"] if which == "after" else o["power_reg"]
                    men = o["after"]["men"] if which == "after" else o["before"]["men"]
                    return p if single else p / men * 60

                rows.sort(key=lambda o: -pm(o, "after"))
                w("### %s\n\n| unit | caste | %s | tier | size | price | why |\n|---|---|---|---|---|---|---|\n" % (title, "regiment" if single else "pm"))
                for o in rows:
                    a, b = pm(o, "after"), pm(o, "before")
                    moved = abs(a - b) > 0.005 * max(1.0, b)
                    fig = ("%.2f → **%.2f**" % (b, a)) if moved else "%.2f" % a
                    size = ("%d → **%d**" % (o["before"]["men"], o["after"]["men"])) if o["before"]["men"] != o["after"]["men"] else "%d" % o["after"]["men"]
                    price = ("%d → **%d**" % (o["cost"], o["new_cost"])) if o["new_cost"] != o["cost"] else "%d" % o["cost"]
                    note = o["note"]
                    if o["action"] in ("lore", "decided") and ". " in note:
                        note = note.split(". ", 1)[1]
                    elif o["action"] == "none" and note.startswith("lore: as vanilla. "):
                        note = note[len("lore: as vanilla. "):]
                    w("| %s | %s | %s | %s | %s | %s | %s |\n" % (o["name"], o["caste"].replace("_", " "), fig, tier(a, o["caste"]), size, price, note.rstrip(".")[:110]))
                w("\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
